### ISSUE TITLE
Conflict with other post processing effect.

### ISSUE THREAD

**Issue by DevSmith0213** [whatisjery/react-fluid-distortion#4]
I shared some part of my code. I tried to add Fluid effect with Bloom at the same time.
But when I add Fluid like following code, Bloom doesn't work. when I add only bloom, it works perfectly.
I want to know what my fault is. Help me.

```
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { Fluid } from "@whatisjery/react-fluid-distortion";

<Canvas className={`w-[100%] h-[100%]`}>
            <EffectComposer>
              <Fluid showBackground={false} rainbow={true} />
              <Bloom
                kernelSize={1}
                luminanceThreshold={0.2}
                luminanceSmoothing={0.4}
                intensity={0.05}
              />
            </EffectComposer>
            <Environment preset="warehouse" environmentIntensity={0.5} />
            <ExplosionModelContainer />
 </Canvas>
```

**Comment by Ameen-Abdullah** [comment]
bro is it fixed ?

**Comment by whatisjery** [comment]
re-renders were causing the post processing pipeline to reinitialize somehow, which removed other effects. It should work now, hopefully. I also added a blend function prop to play with, you can grab it from the postprocessing library to see how it integrates with other effects.
 
` <Fluid blendFunction={BlendFunction.ALPHA} />`

**Comment by Ameen-Abdullah** [comment]
Thank you so much man I was using this yesterday and found this issue, this library is amazing!!

**Comment by Ameen-Abdullah** [comment]
> re-renders were causing the post processing pipeline to reinitialize somehow, which removed other effects. It should work now, hopefully. I also added a blend function prop to play with, you can grab it from the postprocessing library to see how it integrates with other effects.   ` <Fluid blendFunction={BlendFunction.ALPHA} />`

it still doesn't work with other post processing effects, it works for a second but when you refresh it goes back to normal

**Comment by whatisjery** [comment]
> > re-renders were causing the post processing pipeline to reinitialize somehow, which removed other effects. It should work now, hopefully. I also added a blend function prop to play with, you can grab it from the postprocessing library to see how it integrates with other effects.  >  ` > <Fluid blendFunction={BlendFunction.ALPHA} />`
> 
> it still doesn't work with other post processing effects, it works for a second but when you refresh it goes back to normal

I'm not able to reproduce it, do you mind sharing some context ?
